DROP TABLE IF EXISTS COMPOSITE_BATCH_BEANS;


CREATE TABLE COMPOSITE_BATCH_BEANS (
	`ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`NAME` VARCHAR(255) NOT NULL,
	`JOB_NAME` VARCHAR(255) NOT NULL,
	`BATCH_BEAN_TYPE` VARCHAR(50) NULL DEFAULT NULL,
	`PRIORITY` INT(11) NULL DEFAULT NULL,
	PRIMARY KEY (`ID`)
);


 
 -- add filters for claims 
set @batchType = 'PROCESSOR';
set @taskName = 'OhadsTask';
INSERT INTO COMPOSITE_BATCH_BEANS (NAME,PRIORITY,JOB_NAME,BATCH_BEAN_TYPE) VALUES ('Ohad_01_Processor',1, @taskName, @batchType); 
INSERT INTO COMPOSITE_BATCH_BEANS (NAME,PRIORITY,JOB_NAME,BATCH_BEAN_TYPE) VALUES ('Ohad_02_Processor',2, @taskName, @batchType); 

set @batchType = 'WRITER';
INSERT INTO COMPOSITE_BATCH_BEANS (NAME,PRIORITY,JOB_NAME,BATCH_BEAN_TYPE) VALUES ('Ohad_01_Writer',1, @taskName, @batchType); 
INSERT INTO COMPOSITE_BATCH_BEANS (NAME,PRIORITY,JOB_NAME,BATCH_BEAN_TYPE) VALUES ('Ohad_02_Writer',2, @taskName, @batchType); 
INSERT INTO COMPOSITE_BATCH_BEANS (NAME,PRIORITY,JOB_NAME,BATCH_BEAN_TYPE) VALUES ('Ohad_03_Writer',3, @taskName, @batchType); 

